"""Publish view — upload SFT + preference CSVs to Kaggle Datasets."""

import json
import shutil
from pathlib import Path

from textual.app import ComposeResult
from textual.binding import Binding
from textual.containers import Horizontal, Vertical
from textual.widgets import Button, Checkbox, Input, Label, Log, Select, Static
from textual import work

from config import config
from core.merger import SFT_FILENAME, PREF_FILENAME, row_count
from core.uploader import DEFAULT_LICENSE, upload_dataset
from views.widgets import PageHeader

_STATE_FILE = Path(".evalflow_publish_state.json")


def build_dataset_card(
    title: str,
    description: str,
    sft_rows: str,
    pref_pairs: str,
    max_pairs_per_question: int = 8,
) -> str:
    """Generate an honest dataset card (README.md) for a published Evalflow dataset."""
    desc_section = f"\n{description}\n" if description.strip() else ""
    return f"""\
# {title}
{desc_section}
---

## Dataset card

Generated by [Evalflow](https://github.com/4kaws/evalflow) from
[Kaggle Community Benchmarks](https://kaggle.com/benchmarks).

### What this is

Model responses to benchmark tasks, judged automatically by Python assertion
functions (`assert_in`, `assert_equals`, `assert_contains`). The judge is
**binary** — pass or fail, no partial credit, no graded scoring.

### Files

**`evalflow_sft.csv` / `evalflow_sft.parquet`** — {sft_rows} rows (passing responses only)
One row per model response that passed all assertions. Suitable for
supervised fine-tuning (SFT) on objective tasks.

**`evalflow_preferences.csv` / `evalflow_preferences.parquet`** — {pref_pairs} preference pairs
Sampled passing × failing response pairs per question (up to {max_pairs_per_question} per question
to balance model coverage). Column names (`prompt`, `chosen`, `rejected`)
match the HuggingFace TRL `DPOTrainer` format directly.

### Loading the data

```python
# Recommended: use Parquet — types are preserved, no manual JSON parsing
import pandas as pd
sft   = pd.read_parquet("evalflow_sft.parquet")
prefs = pd.read_parquet("evalflow_preferences.parquet")

# Or with HuggingFace datasets (DPO-ready, no column renaming needed)
from datasets import load_dataset
prefs = load_dataset("parquet", data_files="evalflow_preferences.parquet")["train"]
trainer = DPOTrainer(model, train_dataset=prefs, ...)

# CSV fallback — parse the JSON string columns manually
import json
sft = pd.read_csv("evalflow_sft.csv")
sft["messages"]       = sft["messages"].apply(json.loads)
sft["assertions_json"] = sft["assertions_json"].apply(json.loads)
```

### Suitable use cases

- Skill-specific SFT on short objective tasks (math, code, factual recall)
- DPO / RLHF training on correctness preferences (not style preferences)
- Evaluating per-model accuracy on a specific benchmark

### Known limitations

- **Binary signal only.** There is no "how close" measure for failures; a
  response either matches the expected string or it does not.
- **One-line probe tasks.** Questions are short factual probes, not
  long instruction-following tasks. May not generalise to instruction tuning.
- **No style or preference signal.** Preferred responses are objectively
  correct; rejected responses are wrong — this is not a human-preference dataset.
- **No reasoning-chain ground truth.** `ground_truth` is the expected
  string from the assertion, not a step-by-step solution.

### Column reference — `evalflow_sft`

| Column | Description |
|---|---|
| task_name | Benchmark task identifier |
| task_description | Short task description |
| task_definition | Full task definition / rubric |
| model_name | Model slug (e.g. `google/gemma-3-27b-it`) |
| question | Question presented to the model |
| ground_truth | Expected answer (from assertion definition) |
| prompt_template | System prompt, or bare question if none |
| llm_response | The model's response |
| messages | Chat-format JSON — system + user + assistant turns (SFT-ready) |
| score | 1 = passed all assertions (always 1 in this file) |
| reasoning | Failed assertion text, pipe-separated (empty when score=1) |
| assertions_json | Full assertion array with per-assertion pass/fail status |
| judge_model | Judge model slug if an LLM judge was used |
| input_tokens | Input token count |
| output_tokens | Output token count |
| timestamp | ISO-8601 end time |

### Column reference — `evalflow_preferences`

| Column | Description |
|---|---|
| task_name | Benchmark task identifier |
| prompt | The question — matches TRL `DPOTrainer` `prompt` field |
| ground_truth | Expected answer |
| chosen | A response that passed all assertions |
| chosen_model | Model that produced the chosen response |
| rejected | A response that failed at least one assertion |
| rejected_model | Model that produced the rejected response |
| timestamp | ISO-8601 generation time |

---
*Generated by Evalflow*
"""

def _load_publish_state() -> dict:
    try:
        return json.loads(_STATE_FILE.read_text())
    except Exception:
        return {}

def _save_publish_state(state: dict) -> None:
    try:
        _STATE_FILE.write_text(json.dumps(state))
        _STATE_FILE.chmod(0o600)
    except Exception:
        pass


_LICENSE_OPTS = [
    ("CC0 1.0 (Public Domain)", "CC0-1.0"),
    ("CC BY 4.0",               "CC BY 4.0"),
    ("CC BY-SA 4.0",            "CC BY-SA 4.0"),
    ("Apache 2.0",              "Apache 2.0"),
]


class PublishView(Vertical):
    _BTN_IDS = ["publish-btn", "update-btn"]

    BINDINGS = [
        Binding("ctrl+u", "publish_new",    "Publish new",    show=True, key_display="Ctrl+U"),
        Binding("ctrl+e", "publish_update", "Update existing", show=True, key_display="Ctrl+E"),
        Binding("down",   "nav_down",   show=False),
        Binding("up",     "nav_up",     show=False),
        Binding("left",   "nav_left",   show=False),
        Binding("right",  "nav_right",  show=False),
        Binding("escape", "nav_esc",    show=False),
    ]

    def _fid(self) -> str | None:
        return self.app.focused.id if self.app.focused else None

    def _select_btn(self, btn_id: str) -> None:
        for bid in self._BTN_IDS:
            self.query_one(f"#{bid}", Button).variant = (
                "primary" if bid == btn_id else "default"
            )
        self.query_one(f"#{btn_id}", Button).focus()

    def _reset_btns(self) -> None:
        self._select_btn("publish-btn")

    def action_nav_down(self) -> None:
        if self._fid() in self._BTN_IDS:
            return
        self.app.action_focus_next()

    def action_nav_up(self) -> None:
        if self._fid() in self._BTN_IDS:
            self._reset_btns()
            self.query_one("#public-switch", Checkbox).focus()
        else:
            self.app.action_focus_previous()

    def action_nav_left(self) -> None:
        fid = self._fid()
        if fid in self._BTN_IDS:
            idx = self._BTN_IDS.index(fid)
            self._select_btn(self._BTN_IDS[(idx - 1) % 2])

    def action_nav_right(self) -> None:
        fid = self._fid()
        if fid in self._BTN_IDS:
            idx = self._BTN_IDS.index(fid)
            self._select_btn(self._BTN_IDS[(idx + 1) % 2])

    def action_nav_esc(self) -> None:
        if self._fid() in self._BTN_IDS:
            self._reset_btns()
        self.app.action_unfocus()

    DEFAULT_CSS = """
    PublishView { padding: 0; height: 1fr; }

    #publish-body { padding: 1 3; height: 1fr; }

    /* Controls section shrinks to fit form; results section expands to fill */
    #publish-controls { height: auto; }
    #publish-results  { height: 1fr; }

    .section-title { color: #636E7B; text-style: bold; margin-top: 1; margin-bottom: 0; }
    .field-row { layout: horizontal; height: 3; align: left middle; margin-bottom: 0; }
    .field-label { width: 20; height: 3; color: #636E7B; content-align: right middle; padding-right: 2; }
    .field-input { width: 1fr; }
    #btn-row { layout: horizontal; height: 3; margin-top: 1; }
    #btn-row Button { margin-right: 1; }
    #publish-log {
        height: 1fr;
        min-height: 4;
        background: $surface;
        border: round #D0D7DE;
        margin-top: 0;
        padding: 0 1;
    }
    #url-row {
        height: 3;
        margin-top: 1;
        align: left middle;
    }
    #url-panel {
        color: $success;
        height: 3;
        content-align: left middle;
        padding: 0 1;
    }
    #open-dataset-btn {
        margin-left: 1;
    }
    #creds-note { color: #636E7B; margin-bottom: 0; }
    #files-panel {
        height: 4;
        background: $surface;
        border: round #D0D7DE;
        padding: 1 2;
        margin-bottom: 0;
        color: #636E7B;
    }
    """

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self._sft_path:  Path | None = None
        self._pref_path: Path | None = None
        self._state: dict = _load_publish_state()
        self._published_url: str = ""

    def compose(self) -> ComposeResult:
        yield PageHeader(
            "Publish",
            "Upload merged datasets to Kaggle Datasets.",
        )
        with Vertical(id="publish-body"):
            with Vertical(id="publish-controls"):
                yield Static(
                    "Reads KAGGLE_USERNAME + KAGGLE_KEY from .env or ~/.kaggle/kaggle.json",
                    id="creds-note",
                )

                yield Static(self._files_text(), id="files-panel")

                with Horizontal(classes="field-row"):
                    yield Label("Kaggle username:", classes="field-label")
                    yield Input(
                        value=config.kaggle_username or "",
                        placeholder="your-kaggle-username",
                        id="username-input",
                        classes="field-input",
                    )

                with Horizontal(classes="field-row"):
                    yield Label("Dataset title:", classes="field-label")
                    yield Input(
                        value=self._state.get("title", ""),
                        placeholder="e.g. My Benchmark Results",
                        id="title-input",
                        classes="field-input",
                    )

                with Horizontal(classes="field-row"):
                    yield Label("Dataset slug:", classes="field-label")
                    yield Input(
                        value=self._state.get("slug", ""),
                        placeholder="e.g. my-benchmark-results  (URL-safe, no spaces)",
                        id="slug-input",
                        classes="field-input",
                    )

                with Horizontal(classes="field-row"):
                    yield Label("Description:", classes="field-label")
                    yield Input(
                        value=self._state.get("description", ""),
                        placeholder="Describe your benchmark and what models were evaluated",
                        id="description-input",
                        classes="field-input",
                    )

                with Horizontal(classes="field-row"):
                    yield Label("License:", classes="field-label")
                    yield Select(
                        _LICENSE_OPTS,
                        value=self._state.get("license", DEFAULT_LICENSE),
                        id="license-select",
                        classes="field-input",
                    )

                yield Checkbox("Public dataset", value=self._state.get("public", True), id="public-switch")

                with Horizontal(id="btn-row"):
                    yield Button("Publish New",     id="publish-btn", variant="primary")
                    yield Button("Update Existing", id="update-btn",  variant="default")

            with Vertical(id="publish-results"):
                yield Static("Publish Log", classes="section-title")
                yield Log(id="publish-log", highlight=True)
                with Horizontal(id="url-row"):
                    yield Static("", id="url-panel")
                    yield Button("Open Dataset on Kaggle", id="open-dataset-btn", variant="default", disabled=True)

    def set_merged_csvs(self, sft_path: Path, pref_path: Path) -> None:
        """Called by MergeView after a successful merge."""
        self._sft_path  = sft_path
        self._pref_path = pref_path
        self.query_one("#files-panel").update(self._files_text())

    def _files_text(self) -> str:
        if self._sft_path and self._pref_path:
            sft_info  = f"({row_count(self._sft_path)} rows)"
            pref_info = f"({row_count(self._pref_path)} pairs)"
            lines = [
                "  Files to upload:",
                f"  + evalflow_sft.csv             {sft_info}",
                f"  + evalflow_preferences.csv     {pref_info}",
            ]
            if self._sft_path.with_suffix(".parquet").exists():
                lines.append("  + evalflow_sft.parquet + evalflow_preferences.parquet")
            lines.append("  + README.md  (dataset card)")
            return "\n".join(lines)
        return "  No files ready. Go to Merge tab and run a merge first."

    # ------------------------------------------------------------------ #
    #  Events                                                              #
    # ------------------------------------------------------------------ #

    def on_activate(self) -> None:
        self.query_one("#username-input", Input).focus()

    def _save_state(self) -> None:
        _save_publish_state({
            "title":       self.query_one("#title-input",       Input).value,
            "slug":        self.query_one("#slug-input",        Input).value,
            "description": self.query_one("#description-input", Input).value,
            "license":     str(self.query_one("#license-select", Select).value),
            "public":      self.query_one("#public-switch",     Checkbox).value,
        })

    def on_input_changed(self, event: Input.Changed) -> None:
        if event.input.id in ("title-input", "slug-input", "description-input"):
            self._save_state()

    def on_checkbox_changed(self, event: Checkbox.Changed) -> None:
        if event.checkbox.id == "public-switch":
            self._save_state()

    def on_select_changed(self, event: Select.Changed) -> None:
        if event.select.id == "license-select":
            self._save_state()
            self.app.call_after_refresh(
                lambda: self.query_one("#public-switch", Checkbox).focus()
            )

    def on_button_pressed(self, event: Button.Pressed) -> None:
        if event.button.id == "publish-btn":
            self._do_publish(is_update=False)
        elif event.button.id == "update-btn":
            self._do_publish(is_update=True)
        elif event.button.id == "open-dataset-btn":
            if self._published_url:
                import subprocess
                try:
                    subprocess.Popen(
                        ["/mnt/c/Windows/explorer.exe", self._published_url],
                        stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                    )
                except Exception:
                    self.query_one("#publish-log", Log).write_line(f">> {self._published_url}")
            return
        self._reset_btns()
        self.app.set_focus(None)

    def action_publish_new(self) -> None:
        self._do_publish(is_update=False)

    def action_publish_update(self) -> None:
        self._do_publish(is_update=True)

    def _log_from_thread(self, msg: str) -> None:
        self.app.call_from_thread(self.query_one("#publish-log", Log).write_line, msg)

    # ------------------------------------------------------------------ #
    #  Publish                                                             #
    # ------------------------------------------------------------------ #

    def _do_publish(self, is_update: bool) -> None:
        log = self.query_one("#publish-log", Log)
        log.clear()
        self._published_url = ""
        self.query_one("#url-panel").update("")
        self.query_one("#open-dataset-btn", Button).disabled = True

        sft_path  = self._sft_path  or config.output_dir / SFT_FILENAME
        pref_path = self._pref_path or config.output_dir / PREF_FILENAME

        missing = [str(p) for p in [sft_path, pref_path] if not p.exists()]
        if missing:
            log.write_line("[x] Missing files — run Merge first:\n  " + "\n  ".join(missing))
            return

        username    = self.query_one("#username-input",    Input).value.strip()
        title       = self.query_one("#title-input",       Input).value.strip()
        slug        = self.query_one("#slug-input",        Input).value.strip()
        description = self.query_one("#description-input", Input).value.strip()
        license_val = str(self.query_one("#license-select", Select).value)

        if not username:
            log.write_line("[x] Kaggle username is required.")
            return
        if not title:
            log.write_line("[x] Dataset title is required.")
            return
        if not slug:
            log.write_line("[x] Dataset slug is required.")
            return
        if " " in slug:
            log.write_line("[x] Slug cannot contain spaces — use hyphens, e.g. my-benchmark-results")
            return

        # Build staging folder
        staging = config.output_dir / "staging" / slug
        if staging.exists():
            shutil.rmtree(staging)
        staging.mkdir(parents=True)

        shutil.copy2(sft_path,  staging / sft_path.name)
        shutil.copy2(pref_path, staging / pref_path.name)

        # Copy Parquet files if merger wrote them (pyarrow present)
        for parquet in [
            sft_path.with_suffix(".parquet"),
            pref_path.with_suffix(".parquet"),
        ]:
            if parquet.exists():
                shutil.copy2(parquet, staging / parquet.name)

        readme = build_dataset_card(
            title=title,
            description=description,
            sft_rows=row_count(sft_path),
            pref_pairs=row_count(pref_path),
        )
        (staging / "README.md").write_text(readme, encoding="utf-8")

        metadata = {
            "title":       title,
            "id":          f"{username}/{slug}",
            "licenses":    [{"name": license_val}],
            "description": description,
        }
        with open(staging / "dataset-metadata.json", "w") as f:
            json.dump(metadata, f, indent=2)

        log.write_line(f">> Staging: {staging}")
        log.write_line(f"   + {sft_path.name}   ({row_count(sft_path)} rows)")
        log.write_line(f"   + {pref_path.name}   ({row_count(pref_path)} rows)")
        sft_parquet = sft_path.with_suffix(".parquet")
        if sft_parquet.exists():
            log.write_line(f"   + evalflow_sft.parquet + evalflow_preferences.parquet")
        log.write_line(f"   + README.md   (dataset card)\n")

        # Run the blocking upload in a background thread so the UI stays responsive
        self._run_upload(staging, is_update)

    @work(thread=True)
    def _run_upload(self, staging: Path, is_update: bool) -> None:
        result = upload_dataset(
            folder=staging,
            is_update=is_update,
            log_cb=self._log_from_thread,
        )

        def _apply():
            if result.success:
                self._published_url = result.url
                self.query_one("#url-panel").update(f"  {result.url}")
                self.query_one("#open-dataset-btn", Button).disabled = False
            else:
                self.query_one("#publish-log", Log).write_line(f"\n[x] {result.error}")

        self.app.call_from_thread(_apply)

